In [7]:
from os import listdir
from os.path import isfile, join
from matplotlib import pyplot as plt
mypath1 = "../data/processed/white_pawn/"
mypath2 = "../data/processed/black_pawn/"
mypath3 = "../data/processed/other/"
files1 = [f for f in listdir(mypath1) if isfile(join(mypath1, f))]
files2 = [f for f in listdir(mypath2) if isfile(join(mypath2, f))]
files3 = [f for f in listdir(mypath3) if isfile(join(mypath3, f))]
files1, files2, files3


(['1_3.png',
  '1_2.png',
  '1_0.png',
  '1_1.png',
  '1_5.png',
  '1_4.png',
  '1_6.png',
  '1_7.png'],
 ['6_6.png',
  '6_7.png',
  '6_5.png',
  '6_4.png',
  '6_0.png',
  '6_1.png',
  '6_3.png',
  '6_2.png'],
 ['7_5.png',
  '5_7.png',
  '3_1.png',
  '3_0.png',
  '5_6.png',
  '7_4.png',
  '7_6.png',
  '5_4.png',
  '3_2.png',
  '3_3.png',
  '5_5.png',
  '7_7.png',
  '7_3.png',
  '5_1.png',
  '3_7.png',
  '3_6.png',
  '5_0.png',
  '7_2.png',
  '7_0.png',
  '5_2.png',
  '3_4.png',
  '3_5.png',
  '5_3.png',
  '7_1.png',
  '0_0.png',
  '2_2.png',
  '4_4.png',
  '4_5.png',
  '2_3.png',
  '0_1.png',
  '0_3.png',
  '2_1.png',
  '4_7.png',
  '4_6.png',
  '2_0.png',
  '0_2.png',
  '0_6.png',
  '2_4.png',
  '4_2.png',
  '4_3.png',
  '2_5.png',
  '0_7.png',
  '0_5.png',
  '2_7.png',
  '4_1.png',
  '4_0.png',
  '2_6.png',
  '0_4.png'])

In [95]:
X = []
for file in files1:
    data = plt.imread("{}{}".format(mypath1, file))
    data = data[0:283, 0:427, :]
    X.append(data.flatten())
for file in files2:
    data = plt.imread("{}{}".format(mypath2, file))
    data = data[0:283, 0:427, :]
    X.append(data.flatten())
for file in files3:
    data = plt.imread("{}{}".format(mypath3, file))
    data = data[0:283, 0:427, :]
    X.append(data.flatten())
    

In [ ]:
df = pd.DataFrame(X)

In [96]:
X = df.values
import numpy as np
y = np.zeros([len(y), 3])
row = 0
y[row:row+len(files1),0] = 1
row = row + len(files1)
y[row:row+len(files2),1] = 1
row = row + len(files2)
y[row:row+len(files3),2] = 1
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [97]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

In [98]:
rescaledX

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [106]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(1)

In [107]:
model.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [113]:
import pickle
def save_obj(obj, name ):
    with open('obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
    with open('obj/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)

In [114]:
save_obj(model, "model")

In [109]:
prediction = model.predict(X)
prediction


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [ ]:
# # first neural network with keras tutorial
# from numpy import loadtxt
# from keras.models import Sequential
# from keras.layers import Dense
# # load the dataset

# # define the keras model
# model = Sequential()
# model.add(Dense(100, input_dim=483364, activation='relu'))
# model.add(Dense(10, activation='relu'))
# model.add(Dense(3, activation='softmax'))
# # compile the keras model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# # fit the keras model on the dataset
# model.fit(X, y, epochs=10, batch_size=10)
# # evaluate the keras model
# _, accuracy = model.evaluate(X, y)
# print('Accuracy: %.2f' % (accuracy*100))